export {
  BUBU_COPY,
  BUBU_EMPTY_RESPONSE,
  BUBU_FOLLOW_UP_DEFAULTS,
  BUBU_FOLLOW_UP_LOADING,
  BUBU_PROMPTS,
  BUBU_STREAM_LABELS,
  buildAuthDialogTitles,
  buildBubuPrompt,
  createBubuMessageId,
  formatBubuCopy,
  formatAuthErrorMessage,
  getBubuGeneratingLabel,
  getBubuStreamLabel,
  getDonationMessage,
  isTemplateFollowUpSuggestion,
  shouldSkipFollowUpSuggestions,
} from '@/lib/bubu-content'
