export {
  AVATAR_PROMPT_DEEPSEEK,
  AVATAR_PROMPT_GEMINI,
  BBX_PERSONA,
  BUBU_PROMPTS,
  FEATURE_COSTS,
  FEATURE_SENTINELS,
  FORTUNE_PROMPT_DEEPSEEK,
  FORTUNE_PROMPT_GEMINI,
  HEPAN_PROMPT_DEEPSEEK,
  HEPAN_PROMPT_GEMINI,
  LIFEPATH_PROMPT_DEEPSEEK,
  LIFEPATH_PROMPT_GEMINI,
  getFeaturePrompt,
  type FeatureKind,
} from '@/lib/bubu-content'

